# Generated by Django 4.2.2 on 2023-06-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribucion', models.JSONField()),
                ('flota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flotas.flota')),
            ],
        ),
    ]
