# Generated by Django 4.2.7 on 2023-11-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField(default=0)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transporte.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Disenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribucion', models.JSONField()),
                ('flota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transporte.flota')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('flota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transporte.flota')),
            ],
        ),
    ]
